// <auto-generated />
namespace student_attendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Role_and_User_Role_Modules_deleted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Role_and_User_Role_Modules_deleted));
        
        string IMigrationMetadata.Id
        {
            get { return "201904201626150_Role_and_User_Role_Modules_deleted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
