// <auto-generated />
namespace student_attendance.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UserRoles_and_authentications : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserRoles_and_authentications));
        
        string IMigrationMetadata.Id
        {
            get { return "201904200848597_UserRoles_and_authentications"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
